### ISSUE TITLE
 Signature for this request is not valid

### ISSUE THREAD

**Issue by Yazanalsharif** [bhexopen/BHEX-OpenApi#6]
Hello HBTC teams, 

when i am trying to make order request to this endpoint 
[https://api.hbtc.com/openapi/v1/order](url) 
with all parameters the request need and i used `signature` as key secret that i created in my account
```
const sendRequest = () => {
  const currentDate = new Date().getTime();
  const link = 'https://api.hbtc.com/openapi/v1/order'; //

  superagent
    .post(link) // sent post Method to the link
    .query({ symbol: 'ADAUSDT' }) //add query symbol
    .query({ timestamp: currentDate }) //add query timestamp
    .query({ type: 'MARKET' }) //add query type
    .query({
      signature:
        'my secret key that generated when i generate my api key'
    }) //add query signature
    .query({
      quantity: 9
    }) //add query quantity
    .query({ side: 'BUY' }) //add query side
    .set(
      'X-BH-APIKEY',
      'my api key'
    )
    .end((err, res) => {
      return console.log(res.body);
    });
};

```

but its send me an error 
`{
    "code": -1021,
    "msg": "Timestamp for this request is outside of the recvWindow."
}`

and after sync my windows time with windows.server 
it displays new error: 

`{ code: -1022, msg: 'Signature for this request is not valid.' }`

please can you check my code and reply me.

Thank you for interesting

**Comment by oner0812** [comment]
The signature value is not  `secret key`, it's a hash value, created using the SHA-256 algorithm, the post values as message, and `secret key` as SecretKey.
You can see `SIGNED Endpoint Examples` in [api doc](https://apidocs.hbtc.co/general-info)

**Comment by Yazanalsharif** [comment]
yes i solved find the solution early but i forgot to close the issue,

thanks for response.
best regards
